name: JavaScript Unit Tests

on: [ push, pull_request ] # Run on all pushes and PRs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  JSUnitTests:
    name: JavaScript unit tests - Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    strategy:
      matrix:
        node: [16]  # Using Node 16 as specified in package.json engine requirements

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-optional
        
      - name: Verify Node and npm versions
        run: |
          node --version
          npm --version
          
      - name: List installed packages
        run: npm list --depth=0

      - name: Run JavaScript unit tests
        run: npm run test:js 