name: JavaScript Unit Tests

on: [ push, pull_request ] # Run on all pushes and PRs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  JSUnitTests:
    name: JavaScript unit tests - Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    strategy:
      matrix:
        node: [16]  # Using Node 16 as specified in package.json engine requirements

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          # Set npm config to ignore platform checks
          npm config set engine-strict false
          npm config set shrinkwrap false
          npm config set package-lock false
          npm config set audit false
          npm config set fund false
          # Critical setting to ignore platform checks
          npm config set platform-check false
          # Install dependencies with --no-fund and --no-audit for faster installation
          npm install --no-fund --no-audit --no-package-lock --no-shrinkwrap --no-save || true
          # Continue even if there are errors

      - name: Verify Node and npm versions
        run: |
          node --version
          npm --version
          
      - name: List installed packages
        run: npm list --depth=0 || true

      - name: Run JavaScript unit tests
        run: npm run test:js 